# Generated by Django 6.0.1 on 2026-01-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='meals',
            field=models.IntegerField(blank=True, choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед'), ('Полдник', 'Полдник')]),
        ),
    ]
