# Generated by Django 6.0.1 on 2026-01-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_dish_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='meals',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('dinner', 'Обед'), ('snack', 'Полдник')], default='breakfast', max_length=20),
        ),
    ]
