# Generated by Django 6.0.1 on 2026-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_dish_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meals',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('dinner', 'Обед'), ('snack', 'Полдник')], default='breakfast', max_length=20),
        ),
    ]
