# Generated by Django 6.0.1 on 2026-01-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'Салат'), (2, 'Первое блюдо'), (3, 'Второе блюдо'), (4, 'Напиток')], default=0),
        ),
    ]
