# Generated by Django 6.0.1 on 2026-02-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_orders_user_id_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('соок', 'Повар'), ('moderator', 'Модератор')], default='student', max_length=20),
        ),
    ]
