# Generated by Django 6.0.1 on 2026-02-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_dish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meals',
            field=models.CharField(choices=[('all', 'Всегда'), ('breakfast', 'Завтрак'), ('dinner', 'Обед'), ('snack', 'Полдник')], default='breakfast', max_length=20),
        ),
    ]
