# Generated by Django 6.0.1 on 2026-02-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_dish_picture_alter_menu_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='picture',
        ),
    ]
