# Generated by Django 6.0.1 on 2026-02-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
