# Generated by Django 6.0.1 on 2026-02-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='static/img/'),
        ),
    ]
