# Generated by Django 6.0.1 on 2026-02-05 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_dish_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('subscription', 'Абонемент'), ('breakfast', 'Завтрак'), ('dinner', 'Обед'), ('snack', 'Полдник')], default='breakfast', max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish'),
        ),
    ]
