# Generated by Django 6.0.1 on 2026-02-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_price_profile_subscription_alter_menu_dish_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='menu_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='meal_type',
            field=models.CharField(choices=[('all', 'Всегда'), ('breakfast', 'Завтрак'), ('dinner', 'Обед'), ('snack', 'Полдник')], default=False),
        ),
    ]
