# Generated by Django 6.0.1 on 2026-02-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_remove_orders_menu_id_orders_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_id',
        ),
    ]
