# Generated by Django 6.0.1 on 2026-02-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_remove_orders_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='datetime',
        ),
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
