# Generated by Django 6.0.1 on 2026-02-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_alter_review_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='text',
        ),
    ]
