# Generated by Django 6.0.1 on 2026-02-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_rename_orders_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
