# Generated by Django 6.0.1 on 2026-02-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_cheforder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheforder',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
