# Generated by Django 6.0.1 on 2026-02-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_cheforder_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='/static/img/default.png', upload_to='static/img/'),
        ),
    ]
