# Generated by Django 6.0.1 on 2026-02-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_alter_dish_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('chef', 'Повар'), ('moderator', 'Модератор')], default='student', max_length=20),
        ),
    ]
